### ISSUE TITLE
Upload or Download only?

### ISSUE THREAD

**Issue by boxrick** [uktrade/mobius3#37]
This is more of a question than an issue, does mobius3 support upload or download only rather than keeping everything in sync?

In my case, I am running SFTP within Fargate ECS and just want to upload the files and forget about them.

**Comment by michalc** [comment]
@boxrick You could probably use the `--exclude-remote` command line argument, which should be followed by a regex of keys to ignore on the remote side. Something like `--exclude-remote .*` would probably not download anything from the remote, S3, to the local filesystem. I think it would still poll S3 every so often, and go through the list of objects, but it should ignore each one.

**Comment by michalc** [comment]
Will probably close this issue due to inactivity soon.
